sudo: required
language: generic 
service:
  - docker
before_install:
  - docker build -t ibnaveenkashyap/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true ibnaveenkashyap/docker-react npm run test